#!/bin/bash

set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$ROOT_DIR/Scripts"
DEFAULT_COLUMBUS="/usr/local/chem.sw/Columbus"

usage() {
    cat <<EOF
Usage:
  $(basename "$0") initialize

Initialize creates the Columbus directory tree, imports a DRT table and XYZ
geometry, and prepares Scripts/input_values.txt and Scripts/geom.
EOF
}

die() {
    echo "Error: $*" >&2
    exit 1
}

copy_file() {
    local prompt="$1"
    local destination="$2"
    local source_path

    while true; do
        read -r -p "$prompt: " source_path
        if [ -f "$source_path" ]; then
            cp "$source_path" "$destination" || die "Could not copy '$source_path'."
            printf '%s\n' "Copied $(basename "$source_path") to $(dirname "$destination")."
            return
        fi
        echo "File not found: $source_path"
    done
}

initialize() {
    local columbus
    local xyz_name
    local xyz_path

    mkdir -p "$SCRIPTS_DIR" || die "Could not create Scripts directory."

    echo "Columbus input-file setup"
    echo "========================="

    copy_file "Enter the full path to the DRT table (.xlsx)" "$SCRIPTS_DIR/DRT.xlsx"
    python3 "$SCRIPTS_DIR/parse_drt.py" "$SCRIPTS_DIR/DRT.xlsx" || die "DRT parsing failed."

    while true; do
        read -r -p "Enter the full path to the XYZ geometry file: " xyz_path
        if [ -f "$xyz_path" ]; then
            xyz_name="$(basename "$xyz_path")"
            [[ "$xyz_name" == *.xyz ]] || die "The geometry file must have a .xyz extension."
            cp "$xyz_path" "$SCRIPTS_DIR/$xyz_name" || die "Could not copy '$xyz_path'."
            echo "Copied $xyz_name to Scripts."
            break
        fi
        echo "File not found: $xyz_path"
    done

    printf "\n"
    read -r -p "Enter the number of unique atoms in the molecule: " num_unique_atoms
    [[ "$num_unique_atoms" =~ ^[1-9][0-9]*$ ]] || die "Number of unique atoms must be a positive integer."

    printf "\nset num_unique_atoms %s\n" "$num_unique_atoms" >> "$SCRIPTS_DIR/input_values.txt"

    printf "\n"
    read -r -p "Enter Columbus directory [$DEFAULT_COLUMBUS]: " columbus
    columbus=${columbus:-$DEFAULT_COLUMBUS}
    [ -f "$columbus/runc" ] || die "Could not find '$columbus/runc'."
    [ -f "$columbus/colinp" ] || die "Could not find '$columbus/colinp'."
    [ -f "$columbus/xyz2col.x" ] || die "Could not find '$columbus/xyz2col.x'."

    (cd "$SCRIPTS_DIR" && ./make_geom.sh "$xyz_name" "$columbus") || die "Geometry conversion failed."
    
    {
        echo "# Generated by main.sh initialize"
        echo "set COLUMBUS \"$columbus\""
    } >> "$SCRIPTS_DIR/input_values.txt"

    for basis in DZ TZ; do
        for spin in Singlet Triplet; do
            branch="$ROOT_DIR/Columbus/$basis/$spin"
            mkdir -p "$branch/MCSCF-prep" "$branch/MCSCF" \
                "$branch/CISD-prep" "$branch/CISD" \
                "$branch/AQCC-prep" "$branch/AQCC"
        done
    done

    cat > "$SCRIPTS_DIR/config.txt" <<EOF
COLUMBUS=$columbus
EOF

    echo "Initialization complete."
    echo "Use Scripts/run.sh with -mcscf, -cisd-ser, -cisd-par, -aqcc-ser, or -aqcc-par."
}

case "${1:-}" in
    initialize)
        initialize
        ;;
    -h|--help)
        usage
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac